### ISSUE TITLE
Diff reports across threaded trial records

### ISSUE THREAD

**Issue by pwalsh** [opentrials/processors#3]
# Description

Clinical trial data is published in a range of places, including over multiple trial registers. It is a known issue that different publications can declare discrepant facts on a trial. When we have a set of threaded records, we want to run a "diffing" algorithm over the records and pull out these discrepancies as data points in their own right.

# Tasks

* [ ] Write a diff algorithm for a set of threaded records
* [ ] Store the results of such diffs. They are a property of the "ideal" model of the trial on which the records are matched
* [ ] Push this data forward from the warehouse to the main database/API

**Comment by roll** [comment]
closed in favour of https://github.com/opentrials/opentrials/issues/50
